CodeYadShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('Accounts.urls')),
    path('product/', include('Products.urls')),
    path('order/', include('Order.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'

urlpatterns = [
    path('', views.Home.as_view(), name='MainPage')

]

Order/urls.py
from django.urls import path
from . import views

app_name = 'Order'

urlpatterns = [
    path('detail', views.CartView.as_view(), name='cart'),
    path('add/<int:pk>', views.CartHandelView.as_view(), name='cartadd'),
    path('delete/<str:upk>', views.CartDeleteItem.as_view(), name='cartitmedel')
]

Order/models.py
from django.db import models

# Create your models here.

Order/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.views import View

from Order.cart import Cart
from Products.models import Product


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        context = 0
        for item in request.session['cart'].values():
            context += item['quantity'] * int(item['price'])
        return render(self.request, 'Orders/cart.html', {'cart': cart, 'total': context})


class CartHandelView(View):
    def post(self, request, pk):
        size, color, quantity = request.POST.get('size'), request.POST.get('color'), request.POST.get('quantity')
        product = get_object_or_404(Product, id=pk)
        cart = Cart(request)
        cart.add(product, quantity, color, size)
        return redirect('Order:cart')


class CartDeleteItem(View):
    def get(self, request, upk):
        cart = Cart(request)
        cart.delete(upk)
        return redirect('Order:cart')

Order/templates/Orders/cart.html
{% extends 'base.html' %}
{% load static %}


{% block main %}


    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Image</th>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for item in cart %}
                            <tr>
                                <td class="align-middle"><img src="{{ item.product.image.url }}" alt="" style="width: 50px;"></td>
                                <td class="align-middle">{{ item.product.title }}</td>
                                <td class="align-middle">${{ item.price }}</td>
                                <td class="align-middle">{{ item.quantity }}</td>
                                <td class="align-middle">{{ item.color }}</td>
                                <td class="align-middle">{{ item.size }}</td>
                                <td class="align-middle">${{ item.total }}</td>
                                <td class="align-middle"><a href="{% url 'Order:cartitmedel' item.upk %}" class="btn btn-sm btn-danger" ><i class="fa fa-times"></i></a></td>
                            </tr>

                        {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class=" justify-content-between mb-3">
                            {% for item in cart %}
                                <h6>{{ item.product.title }}--{{ item.size }}--{{ item.colot }}${{ item.total }}</h6>

                            {% endfor %}
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ total }}</h5>
                        </div>
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->



{% endblock %}